### ISSUE TITLE
Missing Device List & Plugin (Extension) for Bluetooth Connections

### ISSUE THREAD

**Issue by macminihomebridge** [jeff-winn/homebridge-automower-platform#222]
Hi Jeff!

Thanx for inventing this project, to make Husqvarna Automover accessible via Homebridge and HomeKit!

Unfortunately I can't find a "supported models list". But i think your plugin currently supports only movers with WLAN oder Mobile-connectivity?

Do you think there will be the possibility to produce a plugin that supports local bluetooth-connection for models without the expensive connect module?

Husqvarna provides the Automover Connect App with the option "Automover DIRECT" (Button) that leads to the BT-connection option page. After discovering the mover, one have to provide the PIN-code for the specific mover and can connect to.

I'm not familiar with programming such plugins, but thinking that an "emulation" of the Automover Connect App as a Homebridge-Plugin would be a very nice and may often needed thing... of course that requires a BT-ability of the device on which the Homebridge is running (e.g. Raspi or Mac). The BT-Range of the BT-module in/of the mover is really far ranged. I think that could work well....

Best Regards! ... and I would be very happy to get an reply to this request.

So have a nice day! :)

**Comment by jeff-winn** [comment]
It’s an interesting idea, the issue would really be regarding the Bluetooth stack like you suspect.

There’s a couple huge issues I see with this:
- Range of the Bluetooth is definitely a concern, it would depend entirely on the maximum distance of the mower from the BT receiver. Some people have multiple mowers as well, depending on how large their property is. 60 meters (approx 200 feet) for the Bluetooth 4.1 spec isn’t very far when you start considering property sizes.
- Potentially missing hardware on the Homebridge server. The phone works because they all have Bluetooth these days. A small dongle sticking out of a computer in the basement won’t have anywhere close to the aforementioned max range.
- How to get updates off the mower when things change. That’s what drives the entire plug-in operationally. There was an early  assumption the mower will tell the plug-in about what is happening on it (because that’s how all their current gen mowers work with SMS and their cloud service)
- I don’t have one of these non-SMS mowers, so development would have to happen  completely blind.

The first two would be considerable challenges to overcome on their own. The other two problems make the hurdle too much to overcome. Wish I had a better answer, but it is what it is.

PS: I will add some documentation around the SMS enabled Automower being a requirement, just so people aren’t guessing.

**Comment by jeff-winn** [comment]
For reference, I was contemplating a couple  different approaches:

- (Non-invasive) Bluetooth enabled Arduino hardware running on battery inside the mower casing using an SMS radio.
- (Invasive) If the mower itself provided an extension module port on their board to handle additional hardware.

The non-invasive BT route would have likely been the most stable, the invasive route would essentially be hacking the device.

Any potential option would require a separate application solution to handle the mower connection (like what I did with the VEML7700 plug-in) and expose a web api the plug-in could interact with as Homebridge itself doesn’t do Bluetooth.

**Comment by jeff-winn** [comment]
Have you considered talking to your local Husqvarna dealer about their upgrade module?

https://www.husqvarna.com/us/attachments/automower-connect-kit/

**Comment by macminihomebridge** [comment]
Ok, thanks for the explanation. I thought that it would be easier to "glitch" into the BT-connection between the mover and the iPhone-App. The BT-Range in connection to the property size, I don't see as contradiction. The models with BT are mentioned for smaller grounds by Husqvarna, otherwise one has to run after the mover on large properties. :D 

Your consideration of range and hardware honors you, but also for other use cases divers (hardware) things has to be done to reach certain purposes and7or goals. But I see that's a consistent starting point for IT process or projects.

last: These upgrade modules are a solution, but in my view to expansive (plus working costs). I think about the robonect module... but nearly the same price (round about 180€). Maybe both can be installed by my self...

Thanks for fast reply! ... and keep developing! :)

**Comment by jeff-winn** [comment]
For reference, your asking me to spend my time building it (which my time is effectively my money) rather than spending a low amount to get it connected. 

I’ve easily put 500 hours into this project over the last couple years only because I use it. At the average run rate for contract development conservatively at $50 an hour is at minimum $25k of my time away from my family. I’m definitely not willing to build it since it won’t directly affect me, but I am willing to see if we have an option that would guarantee compatibility if the upgrade was done.

If this works out, you’d have a more reliable solution for a slight investment rather than asking me to put another $25k worth of my time into it.

We’ll see what happens, if it works I’ll throw it in the documentation so others know what to do!

**Comment by macminihomebridge** [comment]
I've to say that I really don't know what to answer to that, but I try:

Sorry, if the my statement to the costs insulted you. Thanks for the existing plugin and that you gave me some time on this explanation.

Your post sounds like I force you to do something outstanding that far from anything that's possible. That's absolutely not the case! I know that everywhere "time is money" but to get this clear: I don't ask you to do something now and for me exclusive and personally. Primary (only!) I just asked for your opinion. Noting more.

ps. Like you do an estimation of time and money, I do this also in my life. But it's not to exploit someone, specially not you.

Thank you for your time!

**Comment by jeff-winn** [comment]
Oh I’m not upset, just making sure we both understood where the money came from  was all! Be it from time invested or a direct purchase of something.

We will see what Husqvarna says, I’m very optimistic that the official module I found will do what we are after and give people a path forward if they choose to do it :)

**Comment by jeff-winn** [comment]
No response yet which is unusual whenever I contact them. Normally I get a response within 48 hours.

They may not answer the question to confirm compatibility with the connect module upgrade.

**Comment by jeff-winn** [comment]
Still no response, if they do not confirm compatibility by Thursday (the email was sent on 12/1) I am going to assume the upgrade will work and just asterisk it that it hasn’t been confirmed in the documentation.

Just need someone to go first and report the upgrade works.

**Comment by jeff-winn** [comment]
Found this indicating the module is the correct one to purchase:

https://www.husqvarna.com/uk/support/husqvarna-self-service/how-to-add-an-automower-robotic-lawn-mower-to-automower-connect-ka-01272/

So, if you would like your mower to become compatible you will need to contact your local Husqvarna dealer and have your mower upgraded.

Hope that helps!
