### ISSUE TITLE
Also have a Motion sensor for Tamper and Fault only, without the "mowing in progress"

### ISSUE THREAD

**Issue by MichelRabozee** [jeff-winn/homebridge-automower-platform#355]
Hi,

**Is your feature request related to a problem? Please describe:**
My feature request is not a problem, only a consequence of me setting notifications to know if a fault or tamering is occuring to a mower, but I do not need to receive a notification that the mower is mowing. And there is no way (as far as I know) to only put a notification on the "fault" and "tamper" without also receiving a notification on "in mowing".

**Describe the solution you'd like:**
Maybe 2 new sensors (activable or not through the config) : a motion sensor only triggered when a fault occurs and a motion sensor triggered when a tampering occurs.
So I could put a notification on only these two sensors.

**Mower:**

* **Year**: 2016
* **Model**: Automower 420

**Comment by jeff-winn** [comment]
To start the conversation, what are you using to configure the notifications? As far as I’m aware, the iOS Home app was unable to attach anything to those events natively.

**Comment by MichelRabozee** [comment]
Hi, when I am speaking of notifications, it is simply the Home app notifications (activity notifications)  I am using.
<img width="407" alt="image" src="https://github.com/user-attachments/assets/fd8d8d0e-f7e6-4953-9123-7d312749f96e">
<img width="406" alt="image" src="https://github.com/user-attachments/assets/492d6302-3835-48ae-b2ff-101352f84aaf">

My request is to be able to have notification when there is a fault or a tampering, but not when the mower is normally mowing (currently, I receive notifications each time it starts mowing).

**Comment by jeff-winn** [comment]
I understand what you’re asking for, I’m trying to simply ascertain whether it’s an issue with how the triggers on the events occur with the motion sensor not working as I had expected.

The reason I chose that sensor is it has all 3 components included with it, and it actually is a motion sensor which was being exposed.

The issue seems to not be with the sensor itself, but merely you only want a notification from one of the 3 components of the same sensor. Which is what the Home app was never very good at setting up.

You might want to try looking at Controller for HomeKit or one of the alternatives that supports those sort of notifications you’re after. I know I had more advanced automations setup with it just because Home couldn’t do it natively.

**Comment by MichelRabozee** [comment]
OK, thank you.

I did not even know there is a possibility to get separate notifications for the 3 motion sensor components. I will investigate Controller for HomeKit (even if I prefer to stay with less extra app as possible).

For information: I was previously using the "homebridge-automower" homebridge plug-in, and I just switched to yours because homebridge-automower is no more maintained and risk to break with HomeBridge 2; also, I prefer the way your plugin work, with client credentials and events instead of polling.
homebridge-automower exposed one motion sensor that will be triggered when the mower needs attention while cutting (either fault or tampering). It is that one which I miss here :-)
(BTW, as I saw someone asking for that: it exposed also a startStopSwitch [switch to handle start / stop until next period] and a startStopUntilFurtherNoticeSwitch [stateless switch to handle stop until further notice]).

Thank you for having read me.

**Comment by jeff-winn** [comment]
Yeah I ended up buying Controller personally because I wanted to setup more advanced scenarios like this and Home itself has a very limited UI versus what it’s actually capable of doing.

I just did this a minute ago with it…
1. In Controller add a server notification with what you want it to tell you when it happens
2. Copy the URL Controller gives you
3. In Controller add an empty automation that occurs when either of the events you’re interested in occur
4. In the Shortcuts app tap on Auromations (at the bottom) and tap on the empty Automation you started
5. In the action, remove the default Set Scene or Accessories option and instead add Get Contents of Web Page
6. Paste the link you got from step 2
8. Enjoy!

Hope that helps!

**Comment by jeff-winn** [comment]
Just to clarify, I do not own or have anything to do with Controller for HomeKit. It’s just the app I use to do the automations, and use Home for normal everyday use with my family.

I personally did the one time lifetime purchase instead of the monthly subscription. I absolutely hate subscription services.

There are other options out there as well that can better manage the HomeKit API. Controller is just the one I chose.

**Comment by MichelRabozee** [comment]
Do not worry, I fully understand. It is just that it is "a bit" expensive just for this exact one purpose here (I bought EVE app some years ago also for 1 small feature I needed at that time, but now it crashes when I tried today to do the same thing as you did, so I am a bit cold feet).  For everything else, I have it covered with just Home app. Thanks again.
